engines:
    phpmd:
        enabled: true
        checks:
            Naming/LongVariable:
                enabled: false
            UnusedFormalParameter:
                enabled: false

exclude_paths:
    - "tests/"
    - "app/"
    - "vender/"
    - "scripts/"
    - "!src/"
