admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

app:
    resource: '@AppBundle/Controller/'
    type: annotation

api:
    resource: '@ApiBundle/Controller/'
    prefix: /api
    type: rest

logout:
    path: /logout

token_login_check:
    path: /token_login_check
    methods: ['POST']

api_login:
    path: /api/login_check
    methods: ['POST']

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
