admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

app:
    resource: '@AppBundle/Controller/'
    type: annotation

logout:
    path: /logout

social_login_check:
    path: /social_login_check
    methods: ['POST']

api_login:
    path: /api/login_check
    methods: ['POST']