logout:
    path: /logout

token_login_check:
    path: /token_login_check
    methods: ['POST']

api_login:
    path: /api/login_check
    methods: ['POST']


admin:
    resource: "@AppBundle/Controller/Admin/"
    type:     annotation
    prefix:   /admin

api:
    resource: '@AppBundle/Controller/Api/'
    prefix: /api
    type: rest

main:
    resource: '@AppBundle/Controller/Main/'
    type: annotation




NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
