admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

app:
    resource: '@AppBundle/Controller/'
    type: annotation

api:
    resource: '@ApiBundle/Controller/'
    type: annotation


logout:
    path: /logout

token_login_check:
    path: /token_login_check
    methods: ['POST']

api_login:
    path: /api/login_check
    methods: ['POST']