# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        CoreBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        core_proivder:
            entity:
                class: CoreBundle:User
                property: email

    role_hierarchy:
        ROLE_ADMIN:  [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_login:
            pattern: ^/api/login_check
            stateless: true
            provider: core_proivder
            guard:
                authenticators:
                    - startsymfony.core.security.api_login_token_guard
                    - startsymfony.core.security.api_login_guard
                entry_point: startsymfony.core.security.api_login_guard

        api:
            pattern: ^/api
            anonymous: ~
            stateless: true
            guard:
                authenticators:
                    - startsymfony.core.security.api_token_guard


        main:
            pattern: ^/*
            anonymous: ~
            provider: core_proivder
            switch_user: true
            form_login:
                login_path: login
                check_path: login
            guard:
                authenticators:
                    - startsymfony.core.security.session_login_token_guard
            logout:
                path: /logout
                target: /

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

