# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        app_proivder:
            entity:
                class: AppBundle:User
                property: email

    role_hierarchy:
        ROLE_ADMIN:  [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_login:
            pattern: ^/api/login_check
            stateless: true
            provider: app_proivder
            guard:
                authenticators:
                    - AppBundle\Security\Guard\ApiLoginGuard
                    - AppBundle\Security\Guard\Token\ApiLoginTokenGuard
                entry_point: AppBundle\Security\Guard\ApiLoginGuard

        api:
            pattern: ^/api
            anonymous: ~
            stateless: true
            guard:
                authenticators:
                    - AppBundle\Security\Guard\Token\ApiTokenGuard


        main:
            pattern: ^/*
            anonymous: ~
            provider: app_proivder
            switch_user: true
            form_login:
                login_path: login
                check_path: login
            guard:
                authenticators:
                    - AppBundle\Security\Guard\Token\SessionLoginTokenGuard
            logout:
                path: /logout
                target: /

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

