# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
   redis_cache_service:
        class: '%snc_redis.doctrine_cache_predis.class%'
        arguments:
            - '@snc_redis.default'

